#!/usr/bin/env bash
#LOCATION OF THIS SCRIPT
ROOT=/var/opt/hermesdeployment
#source enviorment vars
source "$ROOT"/app/env.conf
#source function file
source "$ROOT"/app/functions.sh
ACTION=$1
case $ACTION in
	update) echo "run update";;
	keygen) genkeys $KEYS $2; exit;;
	deploy)
		#Check if --config flas was passed
		if [[ $* == *--config* ]]
		then
			#Load existing config file if it exists
			echo "config file was passed"
			#run deployment script using config file
			exit
		fi;;
esac
#shorthand options
optsetshort=a:r:b:sS:t:hu:g:
#longhad options
optsetlong=account:,repo:,branch:,ssh,src:,target:,help,report,user:,group:,auto,save,bitbucket,service:,afterinstall:,beforeinstall:,config:
if ! options=$(getopt -o $optsetshort -l $optsetlong -- "$@")
then 
	exit 1
fi
eval set -- $options
while [ $# -gt 0 ]
do
	case $1 in
	-h|--help) cat "$SCRIPTDIR"/hermes.man ; exit;;
	-a|--account) ACCOUNT="$2" ; shift;;
	-r|--repo) REPO=$2 ; shift;;
	-b|--branch) BRANCH=$2 ; shift;;
	-s|--ssh) TYPE=ssh;;
	-S|--src) SOURCE=$2 ; shift;;
	-t|--target) TARGET=$2 ; shift;;
	-u|--user) HERMESUSER=$2 ; shift;;
	-g|--group) GROUP=$2 ; shift;;
	--service) SERVICE=$2 ; shift;;
	--bitbucket) SERVICE="BIT";;
	--auto) AUTO=1; SAVE=1;;
	--save) SAVE=1;;
	--report) REPORT="$2" ; shift;;
	--afterinstall) AFTERINSTALL=$2 ; shift;;
	--beforeinstall) BEFOREINSTALL=$2 ;shift;;
	--config) CONFIG=$2 ; shift;;
	esac
	shift
done
#Check if the required parameters are set.
if [ "$ACCOUNT" != "" ] && [ "$REPO" != "" ] && [ "$TARGET" != "" ]
then
	#The below is purly for debugging right now
	echo "Current Configuration"
	echo "Account: $ACCOUNT"
	echo "Repo: $REPO"
	echo "Branch: $BRANCH"
	echo "Type: $TYPE"
	echo "Source: $SOURCE"
	echo "Target: $TARGET"
	echo "User: $HERMESUSER"
	echo "Group: $GROUP"
	echo "Service: $SERVICE"
	echo "BeforeInstall: $BEFOREINSTALL"
	echo "AfterInstall: $AFTERINSTALL"
	#run a deployment
	source "$SCRIPTDIR"/deployment.sh
	#If we are either just saving or automating the configuration
	if [ "$SAVE" = 1 ]
	then
		source "$SCRIPTDIR"/setup.sh
	fi
else
	usage
	if [ "$ACCOUNT" = "" ]
	then
		echo "Error: missing arg <-a|--account>"
	fi
	if [ "$REPO" = "" ]
	then
		echo "Error: missing arg <-r|--repo>"
	fi
	if [ "$TARGET" = "" ]
	then
		echo "Error: missing arg <-t|--target>"
	fi
fi